server.port: 8080

app.name: ewm-main-service

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ewm-main
    username: dbuser
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  jackson:
    serialization:
      INDENT_OUTPUT: true

logging:
  level:
    root: info
    org:
      zalando:
        logbook: trace