CREATE TABLE IF NOT EXISTS public.users (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    email character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    CONSTRAINT users_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.categories (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name character varying(50) NOT NULL,
    CONSTRAINT categories_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.events (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    annotation character varying(2000) NOT NULL,
    confirmed_requests bigint NOT NULL,
    created_on timestamp(3) without time zone NOT NULL,
    description character varying(7000) NOT NULL,
    event_date timestamp(3) without time zone NOT NULL,
    location jsonb,
    paid boolean NOT NULL,
    participant_limit integer NOT NULL,
    published_on timestamp(3) without time zone NOT NULL,
    request_moderation boolean NOT NULL,
    state character varying(255) NOT NULL,
    title character varying(120) NOT NULL,
    views bigint NOT NULL,
    category_id bigint,
    initiator_id bigint,
    CONSTRAINT events_pkey PRIMARY KEY (id),
    CONSTRAINT fkgsyp7tc40dhju9fq5i767kyun FOREIGN KEY (initiator_id)
        REFERENCES public.users (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fko6mla8j1p5bokt4dxrlmgwc28 FOREIGN KEY (category_id)
        REFERENCES public.categories (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT events_state_check CHECK
    (state::text = ANY (ARRAY[
    'PENDING'::character varying,
    'PUBLISHED'::character varying,
    'CANCELED'::character varying
    ]::text[]))
);

CREATE TABLE IF NOT EXISTS public.requests (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created timestamp(3) without time zone,
    status character varying(255),
    event_id bigint,
    requester_id bigint,
    CONSTRAINT requests_pkey PRIMARY KEY (id),
    CONSTRAINT fkeoax2t4j9i61p9lmon3009tr4 FOREIGN KEY (requester_id)
        REFERENCES public.users (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fkm7vtr0204t3xcymbx4sa9t1ot FOREIGN KEY (event_id)
        REFERENCES public.events (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT requests_status_check CHECK
    (status::text = ANY (ARRAY[
    'PENDING'::character varying,
    'PUBLISHED'::character varying,
    'CANCELED'::character varying
    ]::text[]))
);

CREATE TABLE IF NOT EXISTS public.compilations (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    pinned boolean NOT NULL,
    title character varying(255) NOT NULL,
    CONSTRAINT compilations_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.compilation_events (
    compilations_id bigint NOT NULL,
    events_id bigint NOT NULL,
    CONSTRAINT fksu5ujdo34twog11u24n4p5ilw FOREIGN KEY (compilations_id)
        REFERENCES public.compilations (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fktc6qjo6qa1ccbnh8hjldccbjt FOREIGN KEY (events_id)
        REFERENCES public.events (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);
