-- generated by gpt
CREATE TABLE IF NOT EXISTS users (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS categories (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS events (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    annotation VARCHAR(2000) NOT NULL,
    confirmed_requests BIGINT NOT NULL,
    created_on TIMESTAMP NOT NULL,
    description VARCHAR(7000) NOT NULL,
    event_date TIMESTAMP NOT NULL,

    -- jsonb заменили
    location CLOB,

    paid BOOLEAN NOT NULL,
    participant_limit INT NOT NULL,
    published_on TIMESTAMP NOT NULL,
    request_moderation BOOLEAN NOT NULL,

    state VARCHAR(255) NOT NULL,
    title VARCHAR(120) NOT NULL,
    views BIGINT NOT NULL,

    category_id BIGINT,
    initiator_id BIGINT,

    CONSTRAINT fk_events_users
        FOREIGN KEY (initiator_id)
        REFERENCES users(id),

    CONSTRAINT fk_events_categories
        FOREIGN KEY (category_id)
        REFERENCES categories(id),

    CONSTRAINT chk_events_state
        CHECK (state IN ('PENDING','PUBLISHED','CANCELED'))
);

CREATE TABLE IF NOT EXISTS requests (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    created TIMESTAMP,
    status VARCHAR(255),

    event_id BIGINT,
    requester_id BIGINT,

    CONSTRAINT fk_requests_users
        FOREIGN KEY (requester_id)
        REFERENCES users(id),

    CONSTRAINT fk_requests_events
        FOREIGN KEY (event_id)
        REFERENCES events(id),

    CONSTRAINT chk_requests_status
        CHECK (status IN ('PENDING','PUBLISHED','CANCELED'))
);

CREATE TABLE IF NOT EXISTS compilations (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    pinned BOOLEAN NOT NULL,
    title VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS compilation_events (
    compilations_id BIGINT NOT NULL,
    events_id BIGINT NOT NULL,

    CONSTRAINT fk_events_compilations
        FOREIGN KEY (compilations_id)
        REFERENCES compilations(id),

    CONSTRAINT fk_compilations_events
        FOREIGN KEY (events_id)
        REFERENCES events(id)
);